### ISSUE TITLE
./gosa-quickstart: line 40: ./convert_schema.sh: No such file or directory

### ISSUE THREAD

**Issue by Stapper** [mbenkmann/limux-gosa#181]
When running quickstart I get following error message

``` bash
=== Adding GOsa schemata to LDAP config... ===
./gosa-quickstart: line 40: ./convert_schema.sh: No such file or directory
```

If i double check, the file is indeed not present

``` bash
root@farstep:~/limux-gosa/gosa-quickstart/src# ls /etc/ldap/schema/gosa/
fai.ldif            gofon.ldif          goserver.ldif       goto.ldif           rfc2307bis.ldif     trust.ldif
fai.schema          gofon.schema        goserver.schema     goto-mime.ldif      rfc2307bis.schema   trust.schema
gofax.ldif          gosa-samba3.ldif    gosystem.ldif       goto-mime.schema    samba3.ldif
gofax.schema        gosa-samba3.schema  gosystem.schema     goto.schema         samba3.schema
```

**Comment by mbenkmann** [comment]
You're not supposed to run it from the source tree. Build the Debian packages, put them all into a local repository, add that repository to your sources.list, then do apt-get update; apt-get install gosa-quickstart; gosa-quickstart.
This is only supported on Ubuntu trusty, only tested starting from a pristine amd64 server base system, and the resulting system needs a lot of additional work in order to be able to actually install clients from it. The effort is probably not worth it at this time.
