### ISSUE TITLE
Ship GOsa 2.8 in Debian?

### ISSUE THREAD

**Issue by sunweaver** [mbenkmann/limux-gosa#183]
Hi,

I am the Debian maintainer of GOsa and just stumbled over this Git repo. Are you 100% sure that GONICUS has discontinued work on GOsa 2.7? I have a promise to release GOsa 2.7.5 (maintenance release) in Q4/2015.

Is this version of GOsa a generical continuation of the GOsa development or is this GOsa version severely adapted to the use cases in the LiMuX project?

Greets,
Mike (sunweaver at debian.org)

**Comment by mbenkmann** [comment]
I am not in contact with GONICUS. I am just going by the fact that there has been no release in the 2.7 line for years. If they are planning a maintenance release I wouldn't know about it, nor would I care since their code base is so far behind ours quality-wise. Their gosa-si-client/gosa-si-server in particular is fundamentally broken and cannot be fixed to work reliably. Any release that does not replace it with a complete rewrite is simply not worth looking at (at least with respect to FAI-based client installations; GOsa has other functionalities of course that are unaffected by gosa-si).

As far as incompatibilities with GOsa 2.7 go, there isn't anything huge. However I have encountered instances where code that we added relied on certain aspects of our infrastructure. Fixing these issues and writing replacement code is one aspect of this GOsa 2.8 project.

In any case,  at no point will you be able to simply apt-get dist-upgrade from GOsa 2.7 to GOsa 2.8 and keep everything working. In fact, before the first official release of GOsa 2.8 go-susi (the gosa-si-server/client replacement) will be changed to use TLS instead of the current homebrew protocol. This will break communication with existing gosa-si-client/server instances.

So to get to your main question: When GOsa 2.8 is officially released (no date yet, maybe 2016, but could be 2017) it will make sense to include it in Debian because it will provide something very useful to a lot of Debian users, something that currently GOsa 2.7 does not provide. But if there are indeed people who currently use the GOsa 2.7 packages in Debian, it will probably make sense to keep GOsa 2.7 in Debian, too, as long as it can be maintained, to keep those people's installations working. In that case it would make sense to choose a different base name for the GOsa 2.8 packages. We can discuss all of this when I have this project at the point that you can take a Raspberry Pi, run gosa-quickstart on it and get a ready-to-use server for FAI installations of Debian and Ubuntu, including LDAP, DHCP and DNS. This goal is still way in the future.

**Comment by mbenkmann** [comment]
I just reread the readme file and realized that it did not accurately reflect the current state of compatibility between 2.7 and 2.8. I have changed the readme to more closely reflect current (and future) reality.
